# Site settings
baseurl = "https://renonat.github.io/postsecret/"
languageCode = "en-us"
title = "EngSoc Post Secret Service"
theme = "custom-photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    title = "EngSoc Post Secret Wall"
    subtitle = "Have a secret you want to share? EngSoc organizes Post Secret as a way for students to anonymously get anything they want off their chest."
    author = "EngSoc MentalHealth"
    description = "EngSoc Post Secret Service"
    keywords = ""

    # Body background and  text color
    bodybgcolor = "#3d3d3d"
    bodytextcolor = "#f2f2f2"

    # Footer text
    # footer = Footer text
